name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Runs Unit Tests
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
      java-version: '8.0.0'
    - run: ./mvnw test
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Builds The Source Code
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
      java-version: '8.0.0'
    - run: ./mvnw package -Dmaven.test.skip=true